apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeturbo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubeturbo-operator
  template:
    metadata:
      labels:
        name: kubeturbo-operator
    spec:
      serviceAccountName: kubeturbo-operator
      containers:
        - name: kubeturbo-operator
          # Replace this with the built image name
          image: registry.connect.redhat.com/turbonomic/kubeturbo-operator-offline:7.21
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubeturbo-operator"
            - name: RELATED_IMAGE_KUBETURBO
              value: "registry.connect.redhat.com/turbonomic/kubeturbo:7.21.2"